source 'https://rubygems.org'

# This is separate gemfile for building docker image that has all plugins
# for kubernetes log collection agent
# List all required gems here and install via bundler to resolve dependencies
gem "fluentd", ">= 1.19.3"
gem "fluent-plugin-systemd", "=1.0.2"
gem "fluent-plugin-concat", "=2.4.0"
gem "fluent-plugin-prometheus", "=2.0.2"
gem "fluent-plugin-jq", "=0.5.1"
gem 'kubeclient', git: 'https://github.com/ephico2real2/kubeclient.git', ref: '451bff9900258cf380d9f349f48b42e9b72aa558'
gem 'fluent-plugin-kubernetes_metadata_filter', '~> 3.1'
gem "oj", ">=3.11.2"
gem 'multi_json', '~> 1.13'
gem 'net-http-persistent', '~> 4.0'
gem 'openid_connect', '~> 1.1.8'
gem 'prometheus-client', '=2.1.0'
gem 'http_parser.rb', '=0.8.0'
gem "rack", ">=3.0.0"
gem "fluent-plugin-record-modifier", ">=2.1"
gem 'json-jwt', '~> 1.15.0'
gem 'rack-oauth2', '~> 1.19'
gem 'cgi', '~> 0.3.6'
gem 'date', '~> 3.3.3'


gem 'fluent-plugin-splunk-hec', path: 'gem/'
